---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: webhook-role
rules:
- apiGroups:
  - execution.furiko.io
  resources:
  - jobconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - execution.furiko.io
  resources:
  - jobconfigs/status
  verbs:
  - get
- apiGroups:
  - execution.furiko.io
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - execution.furiko.io
  resources:
  - jobs/status
  verbs:
  - get
