---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: controller-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.furiko.io
  resources:
  - jobconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.furiko.io
  resources:
  - jobconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - execution.furiko.io
  resources:
  - jobconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - execution.furiko.io
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.furiko.io
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - execution.furiko.io
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
