run:

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - ifElseChain

issues:
  exclude-rules:
    # Add default exclusions for test files.
    - path: '(.+)_test\.go'
      linters:
        - dupl
        - gocognit
        - gocyclo

    # Excludes nil error return unparam checks.
    - text: "result .* is always nil"
      linters:
        - unparam

    # Excludes "always receives" unparam checks for test files.
    - path: '(.+)_test\.go'
      text: "`.*` always receives `.*`"
      linters:
        - unparam

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
