run:

linters-settings:
  maligned:
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gocognit
        - gocyclo
        - dupl

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
