apiVersion: v1
kind: Service
metadata:
  labels:
    app: execution-webhook
  name: webhook-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: execution-webhook
