# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobconfigs.execution.furiko.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: furiko-system
          name: execution-webhook-service
          path: /convert/jobconfigs.execution.furiko.io
      conversionReviewVersions:
      - v1
