apiVersion: execution.furiko.io/v1alpha1
kind: Job
metadata:
  name: job-sample
spec:
  type: Adhoc

  # Key-value entries to be substituted into the task's template.
  # This will typically be automatically filled in by tools or the controller.
  substitutions:
    option.user-name: "John Smith"
    option.image-tag: "3.15.0"

  # Defines how to create the job.
  template:

    # Defines how many tasks can be created in case of failure.
    maxAttempts: 3

    # Defines how long to wait between retries.
    retryDelaySeconds: 15

    # Maximum duration that a task can be Pending for.
    taskPendingTimeoutSeconds: 1800

    # Defines a template to create a task as a Pod.
    taskTemplate:
      pod:
        spec:
          restartPolicy: Never
          containers:
            - name: job-container
              args:
                - echo
                - "Hello world, ${option.user-name}!"
              env:
                - name: JOB_NAME
                  value: "${job.name}"
                - name: TASK_NAME
                  value: "${task.name}"
                - name: TASK_RETRY_INDEX
                  value: "${task.retry_index}"
              image: "alpine:${option.image-tag}"
              resources:
                limits:
                  cpu: 100m
                  memory: 64Mi
